### ISSUE TITLE
No File Found

### ISSUE THREAD

**Issue by stevie1mat** [jyotirmoy-paul/private-room#1]
import 'package:privateroom/utility/sensitive_constants.dart'; not found in encyption service dart file

**Comment by jyotirmoy-paul** [comment]
Hey @stevie1mat 

That file is intentionally omitted from pushing to GitHub.

`sensitive_constants.dart` file basically contains a password of length 32, stored by the developer, which is used in combination with the **user provided** password to generate a strong password combination, which is finally used.

Basically just to add a layer of security, in case the user password is very easy to guess.

The content of `sensitive_constants.dart` is:
`const developerKey = '<here-goes-your-long-developer-password>';`
