### ISSUE TITLE
Firestore setup

### ISSUE THREAD

**Issue by maxfornacon** [jyotirmoy-paul/private-room#3]
How did you do the Firestore setup? Would be nice if you can give an overview of the collections and fields you have to create in firestore.

Couldn't find it in your article either.

**Comment by jyotirmoy-paul** [comment]
You don't need to create any collections or fields directly in the firestore, the app does that for you whenever you take an action, (such as creating room, sending text messages).

I have not mentioned anything about the fields, as they are present in the model classes used in the app. 

And for setting up firebase, please view the [online documentation](https://firebase.google.com/docs/android/setup)

**Comment by maxfornacon** [comment]
I get following error when I try to run the app.

```
W/Firestore( 8379): (21.3.0) [Firestore]: Listen for Query(rooms) failed: Status{code=PERMISSION_DENIED, description=Missing or insufficient permissions., cause=null}
I/System.out( 8379): com.google.firebase.firestore.FirebaseFirestoreException: PERMISSION_DENIED: Missing or insufficient permissions.
```
Did you change something in the rules section in firebase?

**Comment by jyotirmoy-paul** [comment]
The `google-services.json` file you get when you create a firebase project is not included in the repo. You have to create a new firebase project and get the `google-services.json` first.

**Comment by maxfornacon** [comment]
I did include the google-services.json in my project. The exception says that permissions are missing, so I checked the rules settings in the firebase console.

This is what the default settings are, which I guess block all access to the firestore.
```
rules_version = '2';
service cloud.firestore {
  match /databases/{database}/documents {
    match /{document=**} {
      allow read, write: if false;
    }
  }
}
```
I could get it to work with the following value: `allow read, write: if true`, which is not safe, because every user can access all of the data.
I would highly appreciate if you could share your settings with us, so that we can test your project and get an idea of a safe way to set the rules.

**Comment by jyotirmoy-paul** [comment]
Yeah right, your current rules block the access to any document in firestore. I have not set any production rules for this project, as it was just a hobby project, current active is this itself: `allow read, write: if true`


You can create your own rules after you have populated the database with some initial data, you will get the idea about the fields, documents, and collections used.
