### ISSUE TITLE
Encryption

### ISSUE THREAD

**Issue by Maxmontgelas** [jyotirmoy-paul/private-room#4]
In this case, the only person who could access the chat would be the chat creator.

**Comment by jyotirmoy-paul** [comment]
Anybody joining the room using the same password would also be able to decrypt the chats

**Comment by Maxmontgelas** [comment]
Yes but they would need the same password, so it defeats the object of security when you are having to share the plane text password over other means.

**Comment by jyotirmoy-paul** [comment]
Yes, you are right, but the initial idea was, you can share the key when you are physically close, or something more realistic would be to use any key exchange protocol to exchange the secret key with needed receipts, you can improve the app away lot, but I wanted to keep things simple, thus it's like a sample password to log in.

My main motive was to make an app having E2EE.
