### ISSUE TITLE
What is build folder for?

### ISSUE THREAD

**Issue by Shashwat2708** [jyotirmoy-paul/private-room#6]
Hey, I was trying to understand the application but I am facing difficulty understanding what the build folder is for. It has a bunch of different folders and some even have code in them and honestly I don't think that I have a single clue of what they are being used for.
Can you help me with this?

**Comment by jyotirmoy-paul** [comment]
Hey @Shashwat2708 Can you please tell me which build folder are you referring to? Please paste the folder path.

**Comment by Shashwat2708** [comment]
private-room-master\build
This was the folder.
