### ISSUE TITLE
How to invite others in the room?

### ISSUE THREAD

**Issue by Shashwat2708** [jyotirmoy-paul/private-room#7]
Hi,
I had another doubt. 
I was trying to invite other devices but I was unable to do so. I am not able to see an option where it is written to share the link or join a room.
How do I do so?

**Comment by jyotirmoy-paul** [comment]
Hey @Shashwat2708 There is no way to share a link, to join a room from other device, just search for the room in the main dashboard, and use the password (set while creating the room)

**Comment by Shashwat2708** [comment]
The main dashboard in the Firebase console Or in the app. 
The dashboard is not available on the app.

**Comment by jyotirmoy-paul** [comment]
I am talking about the dashboard_screen in the app, the dashboard screen should contain all the rooms

**Comment by Shashwat2708** [comment]
The main dashboard does show all the rooms but where do i add the id and password to join someone else's room?

**Comment by jyotirmoy-paul** [comment]
tap on any of the room, you will need be prompted to enter the room password

**Comment by jyotirmoy-paul** [comment]
tap on any of the room, you will be prompted to enter the room password

**Comment by Shashwat2708** [comment]
I got that. My doubt is let's say there are two people A and B.
A created a room and joined it. How can be B join the same room and they can chat together? I can't see an option to join a room. That is basically my doubt.
